### ISSUE TITLE
Conditioned generation using image or text

### ISSUE THREAD

**Issue by mrtpk** [OpenMeshLab/MeshXL#5]
Hi @ch3cook-fdu and @ChenFengYe,

Thank you for sharing this amazing work. Surely this will catapult generation of high quality meshes by down stream tasks.

I noticed that you have added provisions for image and text conditioned generation as flags in `main.py`. Are you going to release such a model or are you working on such a image/text conditioned generation process?

Looking forward to your response. Thanks.

Best,
Thomas.

**Comment by ch3cook-fdu** [comment]
Sorry for the late reply. 

We have open-sourced our text-to-mesh generation code and weights. Welcome to try it out!

**Comment by mrtpk** [comment]
Hi @ch3cook-fdu Thank you for your reponse. Your work is just amazing. Thanks for sharing.
